### ISSUE TITLE
Expected behavior only occurring once

### ISSUE THREAD

**Issue by Lootwig** [spkersten/flutter_transparent_pointer#1]
When running this code and tapping the text, the very first tap produces only the "inner" output on the console as expected, but every subsequent tap causes both detectors to fire:

```dart
void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: GestureDetector(
          onTapDown: (_) => print('outer tap down received'),
          child: Container(
            color: Colors.white,
            alignment: Alignment.center,
            child: TransparentPointer(
              child: GestureDetector(
                onTapDown: (_) => print('inner tap down received'),
                child: const Text('TAP ME'),
              ),
            ),
          ),
        ),
      ),
    ),
  );
}
```

This is occurring for me on an Android emulator, flutter stable 3.13.2.

**Comment by spkersten** [comment]
I think you've misunderstood how `TransparentPointer` works. It behaves to its parent as if it is not there, so it won't prevent hits (touches) from reaching a widget that is behind `TransparentPointer`. In a sense, the exact opposite of what you seem to want.

In your example, the outer gesture detector will always be hit because its child is a `Container` which always reports to be hit _when it has a color_ and a tap happens within its bounds. 

The reason it seems to work sometimes has to do with the duration of the tap (not whether it is the first). If the tap is short, the leaf (inner) GestureDetector immediately wins in the gesture arena (because specifying `onTapDown` makes use a `TapGestureRecognizer`) so the outer gesture detector never gets an event. If you tap slowly (or indeed tap-and-hold), it doesn't know yet whether it will be a tap or maybe a drag. In that case, also outer gesture detector receives the touch down event.

To achieve what you want, I think you'll have to split the widget tree using a `Stack` like this:
```dart
void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Stack(
          children: [
            GestureDetector(
              onTapDown: (_) {
                print('outer tap down received');
              },
              child: Container(
                color: Colors.white,
                alignment: Alignment.center,
              ),
            ),
            Center(
              child: GestureDetector(
                onTapDown: (_) {
                  print('inner tap down received');
                },
                child: const Text('TAP ME'),
              ),
            ),
          ],
        ),
      ),
    ),
  );
}
```
The second child (with "inner") is visually in front of the first child in the `Stack`. So `Stack` will not forward touches to the first child if the second child is hit. (`TransparantPointer` exists for cases like this but where you actually want the first child still to be hit even though the second child is in front of it. Hence the name: to make the second child transparant.)
